name: Destroy Terraform to AWS

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Destroy AWS"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Descargar tfstate desde S3
        run: aws s3 cp s3://terraformdestroypedsanlan/terraform.tfstate terraform.tfstate

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # Cambia la versión si necesitas otra

      - name: Inicializar Terraform
        run: terraform init

      - name: Mostrar plan de destrucción
        run: terraform plan -destroy

      - name: Destruir recursos
        id: destroy
        run: terraform destroy -auto-approve

      - name: Subir tfstate actualizado a S3 (opcional)
        if: steps.destroy.outcome == 'success'
        run: aws s3 cp terraform.tfstate s3://terraformdestroypedsanlan/terraform.tfstate
